version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
    pre_install:
      - git update-index --assume-unchanged docs/conf.py ci/requirements/docs.yaml

conda:
  environment: ci/requirements/docs.yaml

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

formats: []